language: ruby
rvm:
  - 2.1.2
#  - 1.9.3
#  - 2.0.0
gemfile:
  - admin/Gemfile
  - backend/Gemfile
bundler_args: --without development --deployment
cache: bundler
script: "cd admin && bundle exec rake test && cd ../backend && bundle exec rake test"
