language: ruby
rvm:
  - 2.1.2
env:
  - ADMIN=true
  - BACKEND=true
gemfile:
  - admin/Gemfile
  - backend/Gemfile
bundler_args: --without development --deployment
cache: bundler
matrix:
  exclude:
    - gemfile: admin/Gemfile
      env: BACKEND=true
    - gemfile: backend/Gemfile
      env: ADMIN=true
before_script:
  - "if [ \"$ADMIN\" == true ]; then cd backend && (bundle exec bin/rails s -p 3002 &) && pid=$! && cd .. && sleep 5 && echo \"Started rails server for backend\"; else echo \"Not starting backend server\"; fi"
  - "if [ \"$ADMIN\" == true ]; then cd admin && echo \"In admin\"; else echo \"Did nothing\"; fi"
  - "if [ \"$BACKEND\" == true ]; then cd backend && echo \"In backend\"; else echo \"Did nothing\"; fi"
script: "bundle exec rake test"
after_script:
  - "if [ \"$ADMIN\" == true ]; then echo $pid && kill -INT $pid; else echo \"Not killing pid\"; fi"