language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-14  ANDROID_ABI=armeabi-v7a

android:
  components:
  - build-tools-20.0.0
  - android-14
  - sys-img-armeabi-v7a-android-14
before_script:
  - cd android
  - ls -l
  - chmod +x ./gradlew

  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest