language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

android:
  components:
  - build-tools-20.0.0
  - android-14
  - sys-img-armeabi-v7a-android-14
before_script:
  - cd android
  - ls -l

  - echo no | android create avd --force -n test -t android-14 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script: ./gradlew connectedAndroidTest